/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examensupletorio;

import CargadeDatos.Carga;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ferchitoo
 */
public class Articulos extends javax.swing.JFrame {

    /**
     * Creates new form Articulos
     */
    public Articulos() {
        initComponents();
        abrirBD();
    }
    

    void mostrar() {
     DefaultTableModel modelo=  new DefaultTableModel();
        modelo.addColumn("Clave_Articulo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio");
        modelo.addColumn("Clave_Fabricante");
        
         modelo.setRowCount(0);
         try {
            Statement comando = conexion.createStatement();
            ResultSet registro = comando.executeQuery("select *from articulos");
            while (registro.next() ) {
                Vector vector=new Vector();
                vector.add(registro.getInt(1));
                vector.add(registro.getString(2));
                vector.add(registro.getInt(3));
                vector.add(registro.getInt(4));
                                
                modelo.addRow(vector);
            }
            
//                jtMostrar.setModel(modelo);
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtclave_articulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtclave_fabricante = new javax.swing.JTextField();
        btn_mostrarProductos = new javax.swing.JButton();
        bton_crear = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaP = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        mostrarArticulo = new javax.swing.JTextArea();
        btnBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Articulos");

        jLabel3.setText("CLAVE_ARTICULO");

        jLabel4.setText("NOMBRE");

        jLabel5.setText("PRECIO");

        jLabel6.setText("CLAVE_FABRICANTE");

        btn_mostrarProductos.setText("Mostrar todos");
        btn_mostrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarProductosActionPerformed(evt);
            }
        });

        bton_crear.setText("Crear");
        bton_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_crearActionPerformed(evt);
            }
        });

        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        tablaP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Clave_Articulo", "Nombre", "Precio", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaP);

        mostrarArticulo.setColumns(20);
        mostrarArticulo.setRows(5);
        jScrollPane2.setViewportView(mostrarArticulo);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jButton1.setText("Mostrar Calculos de Precios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtclave_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtprecio, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                        .addComponent(txtclave_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtnombre)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btn_actualizar)
                                            .addComponent(btnBuscar))
                                        .addGap(29, 29, 29))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btn_mostrarProductos)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(bton_crear)
                                                .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                                .addComponent(txtBuscar, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addGap(20, 20, 20))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtclave_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_mostrarProductos)))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bton_crear)))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtclave_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_actualizar))
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(btnBuscar))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bton_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_crearActionPerformed

try {
            Statement sentencia=conexion.createStatement();
            
            int CLAVE_ART=Integer.parseInt(txtclave_articulo.getText());
            String NOMBRE =  txtnombre.getText();
            int PRECIO=Integer.parseInt(txtprecio.getText());
            int CLAVE_FAB=Integer.parseInt(txtclave_fabricante.getText());

            System.out.printf("%d %s %d %d %n", CLAVE_ART, NOMBRE, PRECIO, CLAVE_FAB);

            String sqlInsert= String.format("INSERT INTO ARTICULOS VALUES('%d','%s', %d, %d)",CLAVE_ART,NOMBRE,PRECIO, CLAVE_FAB);

        int r= sentencia.executeUpdate(sqlInsert);
        System.out.println("Se han modificado "+r+"registros");
       
        conexion.close();

        } catch (SQLException exception) {
            System.out.println("Error al enviar consulta "+exception);

        }
    }//GEN-LAST:event_bton_crearActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
  
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        abrirBD();
          try {
            Statement sentencia=conexion.createStatement();
            //ResultSet registros=sentencia.executeQuery("select * from PROFESOR");
            int CLAVE_ART=Integer.parseInt(txtclave_articulo.getText());
            String NOMBRE =  txtnombre.getText();
            int PRECIO=Integer.parseInt(txtprecio.getText());
            int CLAVE_FAB=Integer.parseInt(txtclave_fabricante.getText());
            

            System.out.printf("%d %s %d %d %n", CLAVE_ART, NOMBRE, PRECIO, CLAVE_FAB);

         
            
            String sqlInsert= String.format("UPDATE ARTICULOS SET CLAVE_ART='%d',NOMBRE='%s', PRECIO='%d',CLAVE_FAB='%d' where CLAVE_FAB='%d'",CLAVE_ART,NOMBRE,PRECIO, CLAVE_FAB);

        int r= sentencia.executeUpdate(sqlInsert);
        System.out.println("Se han modificado "+r+"registros");
        // }
       // registros.close();
        conexion.close();

        } catch (SQLException exception) {
            System.out.println("Error al enviar consulta "+exception);

        }    
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_mostrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarProductosActionPerformed
          abrirBD();
        DefaultTableModel modelo=  new DefaultTableModel();
        modelo.addColumn("CLAVE_ARTICULO");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("PRECIO");
        modelo.addColumn("CLAVE_FABRICANTE");
        
        
      //  DefaultTableModel modelo=  (DefaultTableModel)jTpresentar.getModel();
        modelo.setRowCount(0);
         try {
            Statement comando = conexion.createStatement();
            ResultSet registro = comando.executeQuery("select *from ARTICULOS");
//            ResultSet registro = comando.executeQuery("select distinct nombre,precio *from ARTICULOS;");
            while (registro.next() ) {
                Vector vector=new Vector();
                vector.add(registro.getInt(1));
                vector.add(registro.getString(2));
                vector.add(registro.getInt(3));
                vector.add(registro.getInt(4));
                
                
                modelo.addRow(vector);
            }
            
                tablaP.setModel(modelo);
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btn_mostrarProductosActionPerformed
String cadena="";
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        abrirBD();
         try {
             
             Statement sentencia=conexion.createStatement();
             ResultSet registros=sentencia.executeQuery("select * from ARTICULOS where NOMBRE='Teclado' AND PRECIO='100'");
         
             while (registros.next()) {
                 int CLAVE_ARTICULO=registros.getInt("CLAVE_ARTICULO");
                 String NOMBRE = registros.getString("NOMBRE");
                 int PRECIO=registros.getInt("PRECIO");
                 int CLAVE_FABRICANTE=registros.getInt("CLAVE_FABRICANTE");
                
      
                 
                //System.out.printf("%s %s %s %s %s %d %d %n", CEDULA, NOMBRES, APELLIDOS, CARRERA, TIPOPROFESOR, HORASCLASE, HORASCOMPLEMENTARIAS);
                cadena=cadena+CLAVE_ARTICULO+" "+NOMBRE+" "+PRECIO+" "+CLAVE_FABRICANTE+"\n";
                 //System.out.println(CEDULA+" "+NOMBRES+" "+APELLIDOS+" "+CARRERA+" "+" "+TIPOPROFESOR+"\n");

           }
             registros.close();
             conexion.close();
            
        } catch (SQLException ex) {
            System.out.println("Error al enviar consulta "+ex);
        }
         mostrarArticulo.setText(cadena);
    }//GEN-LAST:event_btnBuscarActionPerformed
     String aux="";
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        abrirBD();
        DefaultTableModel modelo=  new DefaultTableModel();
        modelo.addColumn("CLAVE_ARTICULO");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("PRECIO");
        modelo.addColumn("CLAVE_FABRICANTE");
        
        
      //  DefaultTableModel modelo=  (DefaultTableModel)jTpresentar.getModel();
        modelo.setRowCount(0);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Articulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_mostrarProductos;
    private javax.swing.JButton bton_crear;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea mostrarArticulo;
    private javax.swing.JTable tablaP;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtclave_articulo;
    private javax.swing.JTextField txtclave_fabricante;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
  Connection conexion=null;
     public void abrirBD(){
     
       try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            System.out.println("Driver cargado !!!");
        } catch (ClassNotFoundException cnfe) {
            System.out.println("Error al cargar Driver "+cnfe);   
        }
        
        try {
            String urlbd="jdbc:derby://localhost:1527/Articulos";
            conexion = DriverManager.getConnection(urlbd, "administrador","admin");
             System.out.println("Conexion satisfactoria !!!");
        } catch (SQLException sqlex) {
            System.out.println("Error al establecer conexion a la BD: "+sqlex);
        }

     


     }

}
